-- Heartbeat table for Supabase keep-alive pings
-- This table is used by GitHub Actions to ping Supabase and prevent pausing
-- Run this in Supabase Dashboard → SQL Editor

-- Create the heartbeat table
create table if not exists public.heartbeat (
  id bigint generated by default as identity primary key,
  touched_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.heartbeat enable row level security;

-- Allow anonymous (anon key) to read it (SELECT)
-- This allows GitHub Actions to ping using the public anon key
create policy "anon can read heartbeat"
on public.heartbeat
for select
to anon
using (true);

-- Insert one initial row (so the select always returns something)
insert into public.heartbeat default values
on conflict do nothing;

