'use client';

import { useMemo } from 'react';
import { createAvatar } from '@dicebear/core';
import { lorelei, shapes, initials, identicon } from '@dicebear/collection';

// SVG is generated by DiceBear from seed/style only — no user HTML. Do not use
// dangerouslySetInnerHTML for user-supplied or uploaded SVG/HTML without a sanitizer (e.g. DOMPurify).

export default function DiceBearAvatar({ seed, style = 'lorelei', size = 64, className = '' }) {
  const avatarSvg = useMemo(() => {
    let avatarStyle;
    
    switch (style) {
      case 'shapes':
        avatarStyle = shapes;
        break;
      case 'initials':
        avatarStyle = initials;
        break;
      case 'identicon':
        avatarStyle = identicon;
        break;
      default:
        avatarStyle = lorelei;
    }

    const avatar = createAvatar(avatarStyle, {
      seed: seed || 'default',
      size: size,
      radius: 50,
    });

    return avatar.toString();
  }, [seed, style, size]);

  return (
    <div 
      className={`inline-block ${className}`}
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={{ __html: avatarSvg }}
    />
  );
}

